// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function DecrInt(arg1, arg2) {
  return window['go']['main']['App']['DecrInt'](arg1, arg2);
}

export function DeleteField(arg1) {
  return window['go']['main']['App']['DeleteField'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetState(arg1) {
  return window['go']['main']['App']['GetState'](arg1);
}

export function IncrInt(arg1, arg2) {
  return window['go']['main']['App']['IncrInt'](arg1, arg2);
}

export function ListTopics() {
  return window['go']['main']['App']['ListTopics']();
}

export function Metrics() {
  return window['go']['main']['App']['Metrics']();
}

export function Publish(arg1, arg2, arg3) {
  return window['go']['main']['App']['Publish'](arg1, arg2, arg3);
}

export function SetInt(arg1, arg2) {
  return window['go']['main']['App']['SetInt'](arg1, arg2);
}

export function SetString(arg1, arg2) {
  return window['go']['main']['App']['SetString'](arg1, arg2);
}

export function Subscribe(arg1, arg2) {
  return window['go']['main']['App']['Subscribe'](arg1, arg2);
}

export function TimeNow(arg1) {
  return window['go']['main']['App']['TimeNow'](arg1);
}

export function Unsubscribe(arg1) {
  return window['go']['main']['App']['Unsubscribe'](arg1);
}
