// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string):Promise<void>;

export function DecrInt(arg1:string,arg2:number):Promise<number>;

export function DeleteField(arg1:string):Promise<number>;

export function Disconnect():Promise<void>;

export function GetState(arg1:string):Promise<string>;

export function IncrInt(arg1:string,arg2:number):Promise<number>;

export function ListTopics():Promise<Array<string>>;

export function Metrics():Promise<string>;

export function Publish(arg1:string,arg2:string,arg3:string):Promise<number>;

export function SetInt(arg1:string,arg2:number):Promise<number>;

export function SetString(arg1:string,arg2:string):Promise<number>;

export function Subscribe(arg1:string,arg2:string):Promise<void>;

export function TimeNow(arg1:string):Promise<number>;

export function Unsubscribe(arg1:string):Promise<void>;
